name: Generate PluginMaster
on: 
  page_build:
  workflow_dispatch:
  push:
    branches:
      - stg

jobs:
  generate-stg:
    name: Generate stg PluginMaster
    if: contains(github.event.head_commit.message, 'update:')
    runs-on: windows-2019
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v1
      - name: Run generator
        run: .\Make-PluginMaster-stg.ps1
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Generate PluginMaster" -a
      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: stg

  create-pr:
    name: Create PR
    if: contains(github.event.head_commit.message, '[Release]')
    runs-on: ubuntu-latest
    needs: generate-stg
    steps:
      - uses: actions/checkout@v2
      - name: Create release pr
        run: gh pr create -B "master" -t "Publication： Plugins" -a ryon5541 -b ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate:
    name: Generate PluginMaster
    if: startsWith(github.event.head_commit.message, 'Merge pull request')
    runs-on: windows-2019
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v1
      - name: Run generator
        run: .\Make-PluginMaster.ps1
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Generate PluginMaster" -a
      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
  
  
